server:
  port: 7002

eureka:
  instance:
    #hostname: localhost
    hostname: eureka7002.com
  client:
    # 表示是否将自己注册进 EurekaServer 默认为 true
    register-with-eureka: false
    # 是否从 EurekaServer 抓取已有的注册信息，默认为 true. 单节点无所谓，集群必须设置为 true，才能配置 ribbon 使用负载均衡
    fetch-registry: false
    service-url:
      # 设置Eureka Server访问地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://eureka7001.com:7001/eureka



