server:
  port: 9999

spring:
  application:
    name: cloud-gateway-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://106.15.177.236:3306/night?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          lower-case-service-id: true #在eureka中，服务是以大写的形式注册的，可以转化成小写
      routes:
        - id: payment-service  # 路由ID，没有固定规则，但要求唯一
          # uri: http://localhost:9001 # 匹配后提供服务的地址
          uri: lb://cloud-payment-service # 匹配后提供服务的服务名
          predicates:
            - Path=/payment/** # 断言,路劲相匹配的进行转发

eureka:
  client:
    # 表示是否将自己注册进 EurekaServer 默认为 true
    register-with-eureka: true
    # 是否从 EurekaServer 抓取已有的注册信息，默认为 true. 单节点无所谓，集群必须设置为 true，才能配置 ribbon 使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
      # 集群版
      # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
